name: OCI Terraform CI/CD

on:
  push:
    branches:
      - main
env:
  TF_LOG: DEBUG
  TF_VAR_fingerprint: ${{ secrets.FINGERPRINT }}
  TF_VAR_tenancy_ocid: ${{ secrets.TENANCY_OCID }}
  TF_VAR_user_ocid: ${{ secrets.USER_OCID }}
  TF_VAR_region: ${{ secrets.REGION }}
  TF_VAR_private_key_path: ${{secrets.KEY_FILE}}

jobs:
  terraform:
    name: Deploy to OCI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Write Config & Key Files'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user_ocid=${{secrets.USER_OCID}}" >> ~/.oci/config
          echo "region=${{secrets.REGION}}" >> ~/.oci/config
          echo "tenancy_ocid=${{secrets.TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "${{secrets.KEY_FILE}}" >> ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          echo "fingerprint=${{secrets.FINGERPRINT}}" >> ~/.oci/config


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.1


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
